from mongoengine import *


class User(Document):
    sno=IntField()
    user_id=IntField()
    name=StringField()
    password=StringField()
    roles=StringField()
    department=StringField()
    Active_Status=StringField(default='A')

class vendor_master_data(Document):
    sno=IntField(uniuqe=True)
    company_name=StringField()
    company_code= StringField()
    company_address= StringField()
    city= StringField()
    state= StringField()
    pincode= StringField()
    gst= StringField()
    # phone_number= StringField()
    mobilenumber=StringField()
    created_on= DateTimeField()
    created_by= StringField()
    modify_by=StringField()
    modify_on=DateTimeField()
    status= StringField(default='A')

class generate_bill(Document):
    sno= IntField(unique=True)
    invoice_no= StringField()
    eway_number= StringField()
    purchase_number= StringField()
    purchase_date= DateField()
    company_name= StringField()
    billing_address= StringField()
    shipping_address= StringField()
    gst_number= StringField()
    vechine_number= StringField()
    created_on= DateTimeField()
    created_by= StringField()
    status= StringField(default='A')

class bill_product_details(Document):
    sno= IntField()
    inv_bill= StringField()
    product_name= StringField()
    Hsn= StringField()
    Quantity= FloatField()
    UOM_data= StringField()
    price= FloatField()
    Amount= FloatField()
    created_on= DateTimeField()
    created_by= StringField()
    status= StringField(default='A')


class bill_details(Document):
    sno= IntField()
    company_name= StringField()
    bill_id= StringField()
    inv_bill= StringField()
    total_amount= FloatField()
    sgst= FloatField()
    cgst= FloatField()
    total_amount_after_tax= FloatField()
    file_path= StringField()
    qr_code= StringField()
    created_on= DateTimeField()
    created_by= StringField()
    status= StringField(default='A')